name: run-one-variable
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-model-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install matplotlib
          pip install ipywidgets
      
      - name: Execute the python code and plot the model
        run: python linear_regression_models/one_variable.py
